version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/react-app-demo/demo-app/build # Where the build files will be copied on the EC2 instance

hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 300
      runas: ec2-user
