version: 0.2

phases:
  install:
    commands:
      - echo "Navigating to the demo-app directory..."
      - cd demo-app  # Navigate to the directory containing package.json
      - echo "Installing dependencies..."
      - npm install  # Install dependencies in the demo-app directory
  build:
    commands:
      - echo "Building the React app..."
      - npm run build  # Run the build command inside the demo-app directory

artifacts:
  files:
    - '**/*'  # Include all files in the build output
  base-directory: build  # Artifacts where npm run build places the production files
