version: 0.2

phases:
  install:
    commands:
      - pwd # Ensure you're in the right directory
      - ls # List the files to check where you are
      - rm -rf node_modules
      - npm cache clean --force
      - npm install
      - npm list # Check installed dependencies
  build:
    commands:
      - pwd # Ensure you're still in the correct directory
      - ls # List files again to verify build context
      - npm run build # Run the build command

artifacts:
  files:
    - "**/*"
  base-directory: build # Assuming the build output goes here
