version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Navigating to the demo-app directory for install..."
      - cd demo-app # Navigate to the demo-app directory
      - npm install # Install dependencies in the correct directory
  build:
    commands:
      - echo "Building the React app..."
      - pwd
      - ls # Ensure you are in the correct directory
      - npm run build # Run the build command

artifacts:
  files:
    - "**/*"
  base-directory: demo-app/build # Assuming the build output goes here
